### ISSUE TITLE
debian packaging - missing vts configs

### ISSUE THREAD

**Issue by crpb** [grommunio/admin-configs#4]
@grantma 👋🏼 

The package 'grommunio-admin-common' is missing the configuration snippets for the nginx-module-vts.

ref: https://github.com/grommunio/admin-api/issues/49

### suse appliance
```
root@grom-test-1:/tmp/tmp.DuAq6Z0Z5J# rpm -q grommunio-admin-common
grommunio-admin-common-42.e17ec55-lp156.37.1.noarch
root@grom-test-1:/tmp/tmp.DuAq6Z0Z5J# rpm -q --filesbypkg grommunio-admin-common
grommunio-admin-common    /etc/grommunio-admin-common
grommunio-admin-common    /etc/grommunio-admin-common/nginx.d
grommunio-admin-common    /etc/nginx
grommunio-admin-common    /etc/nginx/conf.d
grommunio-admin-common    /etc/nginx/conf.d/grommunio-admin.conf
grommunio-admin-common    /usr/sbin/grommunio-postfix
grommunio-admin-common    /usr/sbin/grommunio-repo
grommunio-admin-common    /usr/sbin/grommunio-update
grommunio-admin-common    /usr/share/grommunio-admin-common
grommunio-admin-common    /usr/share/grommunio-admin-common/nginx-ssl-params.conf
grommunio-admin-common    /usr/share/grommunio-admin-common/nginx-ssl.conf
grommunio-admin-common    /usr/share/grommunio-admin-common/nginx.conf
grommunio-admin-common    /usr/share/grommunio-admin-common/nginx.d
grommunio-admin-common    /usr/share/grommunio-admin-common/nginx.d/antispam.conf
grommunio-admin-common    /usr/share/grommunio-admin-common/nginx.d/compression.conf
grommunio-admin-common    /usr/share/grommunio-admin-common/nginx.d/robots.conf
grommunio-admin-common    /usr/share/grommunio-admin-common/nginx.d/security.conf
grommunio-admin-common    /usr/share/grommunio-admin-common/traffic-dfl.conf
grommunio-admin-common    /usr/share/grommunio-admin-common/traffic-sm.conf
```

### Debian Trixie
```
root@grom-deb:/tmp/tmp.RsNkNLsSfB# apt list grommunio-admin-common
grommunio-admin-common/unknown,now 42.e17ec55-1+37.1 amd64 [installed]
root@grom-deb:/tmp/tmp.RsNkNLsSfB# dpkg -L grommunio-admin-common
/.
/etc
/etc/grommunio-admin-common
/etc/grommunio-admin-common/nginx.d
/etc/nginx
/etc/nginx/conf.d
/etc/nginx/conf.d/grommunio-admin.conf
/usr
/usr/sbin
/usr/sbin/grommunio-postfix
/usr/sbin/grommunio-repo
/usr/sbin/grommunio-update
/usr/share
/usr/share/doc
/usr/share/doc/grommunio-admin-common
/usr/share/doc/grommunio-admin-common/changelog.Debian.gz
/usr/share/doc/grommunio-admin-common/copyright
/usr/share/grommunio-admin-common
/usr/share/grommunio-admin-common/nginx-ssl-params.conf
/usr/share/grommunio-admin-common/nginx-ssl.conf
/usr/share/grommunio-admin-common/nginx.conf
/usr/share/grommunio-admin-common/nginx.d
/usr/share/grommunio-admin-common/nginx.d/antispam.conf
/usr/share/grommunio-admin-common/nginx.d/robots.conf
/usr/share/grommunio-admin-common/nginx.d/security.conf
```

**Comment by grantma** [comment]
Fixed this in packaging build.grommunio.com.  Should be available via the community repositories by now.  Briefly changed packaging to use dh_nginx, and thus auto generate set up scripts.  Also added Conflicts: libnginx-mod-vts for when the package does end up in Debian.

**Comment by grantma** [comment]
As fixed above, closing issue

**Comment by crpb** [comment]
hmm.. i'm guessing the build is stuck in that ominous https://build.grommunio.com/ 🙊

**Comment by crpb** [comment]
@grantma 

the files traffic-{dfl,sm}.conf are still missing 😢

**Comment by grantma** [comment]
Yep, found why fix was not propagating.  should be coming out tomorrow.

**Comment by crpb** [comment]
hey, @grantma

these files are still missing in `grommunio-admin-common/unknown,now 42.e17ec55-1+37.1 amd64 [installed]`

https://github.com/grommunio/admin-configs/blob/e17ec555fb20cc3fa53cc4a6db6f3f96dce485bd/usr/share/grommunio-admin-common/traffic-sm.conf#L1-L4

https://github.com/grommunio/admin-configs/blob/e17ec555fb20cc3fa53cc4a6db6f3f96dce485bd/usr/share/grommunio-admin-common/traffic-dfl.conf#L1


HAHAHAAA i found the problem after beeing totaly confused as the files are in the source packages 🙉 🙈 🙊 

```
root@grom-deb:/tmp/tmp.kyWoLdjhSa# wget https://download.grommunio.com/community/Debian_13/grommunio-admin-common_42.e17ec55-1%2B37.1.diff.gz https://download.grommunio.com/community/Debian_13/grommunio-admin-common_42.e17ec55-1%2B37.1.dsc https://download.grommunio.com/community/Debian_13/grommunio-admin-common_42.e17ec55.orig.tar.gz
--2025-10-25 08:56:10--  https://download.grommunio.com/community/Debian_13/grommunio-admin-common_42.e17ec55-1%2B37.1.diff.gz
Resolving download.grommunio.com (download.grommunio.com)... 104.26.4.226, 104.26.5.226, 172.67.73.226, ...
Connecting to download.grommunio.com (download.grommunio.com)|104.26.4.226|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13517 (13K) [application/octet-stream]
Saving to: ‘grommunio-admin-common_42.e17ec55-1+37.1.diff.gz’

grommunio-admin-common_42.e17ec55-1+37. 100%[==============================================================================>]  13.20K  --.-KB/s    in 0s

2025-10-25 08:56:10 (32.3 MB/s) - ‘grommunio-admin-common_42.e17ec55-1+37.1.diff.gz’ saved [13517/13517]

--2025-10-25 08:56:10--  https://download.grommunio.com/community/Debian_13/grommunio-admin-common_42.e17ec55-1%2B37.1.dsc
Reusing existing connection to download.grommunio.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 933 [application/octet-stream]
Saving to: ‘grommunio-admin-common_42.e17ec55-1+37.1.dsc’

grommunio-admin-common_42.e17ec55-1+37. 100%[==============================================================================>]     933  --.-KB/s    in 0s

2025-10-25 08:56:10 (19.3 MB/s) - ‘grommunio-admin-common_42.e17ec55-1+37.1.dsc’ saved [933/933]

--2025-10-25 08:56:10--  https://download.grommunio.com/community/Debian_13/grommunio-admin-common_42.e17ec55.orig.tar.gz
Reusing existing connection to download.grommunio.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 6588 (6.4K) [application/octet-stream]
Saving to: ‘grommunio-admin-common_42.e17ec55.orig.tar.gz’

grommunio-admin-common_42.e17ec55.orig. 100%[==============================================================================>]   6.43K  --.-KB/s    in 0s

2025-10-25 08:56:10 (38.1 MB/s) - ‘grommunio-admin-common_42.e17ec55.orig.tar.gz’ saved [6588/6588]

FINISHED --2025-10-25 08:56:10--
Total wall clock time: 0.4s
Downloaded: 3 files, 21K in 0.001s (32.9 MB/s)
root@grom-deb:/tmp/tmp.kyWoLdjhSa# dpkg-source -x grommunio-admin-common_42.e17ec55-1+37.1.dsc
dpkg-source: warning: extracting unsigned source package (grommunio-admin-common_42.e17ec55-1+37.1.dsc)
dpkg-source: info: extracting grommunio-admin-common in grommunio-admin-common-42.e17ec55
dpkg-source: info: unpacking grommunio-admin-common_42.e17ec55.orig.tar.gz
dpkg-source: info: applying grommunio-admin-common_42.e17ec55-1+37.1.diff.gz
root@grom-deb:/tmp/tmp.kyWoLdjhSa# cat grommunio-admin-common-42.e17ec55/debian/grommunio-admin-common.install
etc/
usr/
root@grom-deb:/tmp/tmp.kyWoLdjhSa# find grommunio-admin-common-42.e17ec55/usr/
grommunio-admin-common-42.e17ec55/usr/
grommunio-admin-common-42.e17ec55/usr/share
grommunio-admin-common-42.e17ec55/usr/share/grommunio-admin-common
grommunio-admin-common-42.e17ec55/usr/share/grommunio-admin-common/traffic-sm.conf
grommunio-admin-common-42.e17ec55/usr/share/grommunio-admin-common/traffic-dfl.conf
grommunio-admin-common-42.e17ec55/usr/share/grommunio-admin-common/nginx.d
grommunio-admin-common-42.e17ec55/usr/share/grommunio-admin-common/nginx.d/security.conf
grommunio-admin-common-42.e17ec55/usr/share/grommunio-admin-common/nginx.d/robots.conf
grommunio-admin-common-42.e17ec55/usr/share/grommunio-admin-common/nginx.d/compression.conf
grommunio-admin-common-42.e17ec55/usr/share/grommunio-admin-common/nginx.d/antispam.conf
grommunio-admin-common-42.e17ec55/usr/share/grommunio-admin-common/nginx.conf
grommunio-admin-common-42.e17ec55/usr/share/grommunio-admin-common/nginx-ssl.conf
grommunio-admin-common-42.e17ec55/usr/share/grommunio-admin-common/nginx-ssl-params.conf
grommunio-admin-common-42.e17ec55/usr/sbin
grommunio-admin-common-42.e17ec55/usr/sbin/grommunio-update
grommunio-admin-common-42.e17ec55/usr/sbin/grommunio-repo
grommunio-admin-common-42.e17ec55/usr/sbin/grommunio-postfix
```
# PLEASE UPDATE debian/rules
```
root@grom-deb:/tmp/tmp.kyWoLdjhSa/grommunio-admin-common-42.e17ec55/debian# cat rules
#!/usr/bin/make -f
INSTDIR=debian/tmp

%:
        -mkdir -p debian/source && echo "1.0" > debian/source/format
        dh $@

override_dh_auto_install:
        mkdir -p "${INSTDIR}"
        mv -v etc usr "${INSTDIR}/"
        find "${INSTDIR}" -type f -name .empty -delete
        # Don't have the modules on DE/UB
        rm -fv "${INSTDIR}/usr/share/grommunio-admin-common/nginx.d/compression.conf"
        rm -fv "${INSTDIR}/usr/share/grommunio-admin-common/traffic-sm.conf"
        rm -fv "${INSTDIR}/usr/share/grommunio-admin-common/traffic-dfl.conf"

```

EDIT:
And as BROTLI is in Debian since Bookworm please also remove the `rm` for the compression.conf

**Comment by crpb** [comment]
And as this is kinda related i would suggest adding some `Depends:` or at least `Recommends:` to this package or `grommunio-common` maybe.

```
root@grom-deb:/tmp/tmp.VNxipNw6Wz# apt rdepends libnginx-mod-http-brotli-static libnginx-mod-http-brotli-filter nginx-module-vts
libnginx-mod-http-brotli-static
Reverse Depends:
libnginx-mod-http-brotli-filter
Reverse Depends:
nginx-module-vts
Reverse Depends:
  Depends: nginx-module-vts-dbgsym (= 0.2.4-1+14.1)
```

**Comment by grantma** [comment]
Hi!

I'll check again.  The module load files are in the nginx-module-vts
package. So youre looking for the  vts config files for Grommunio? I
thought the load files were all that were needed ...

Cheers,

Matt

**Comment by crpb** [comment]
The [admin-api vhostStatus endpoint](https://github.com/grommunio/admin-api/blob/021a23cd996acacc090f9f2d0a1eb4092b8c7564/endpoints/system/misc.py#L209-L221) will only work with those extra configuration files. I don't even use that myself but i know enough people who make noise when the status site in the admin-web doesn't work 🙈 

I think that `override_dh_autoinstall` could just be deleted if the files in debian/* were recently changed to handle it the 🐮 way?
```
override_dh_auto_install:
        mkdir -p "${INSTDIR}"
        mv -v etc usr "${INSTDIR}/"
        find "${INSTDIR}" -type f -name .empty -delete
        # Don't have the modules on DE/UB
        rm -fv "${INSTDIR}/usr/share/grommunio-admin-common/nginx.d/compression.conf"
        rm -fv "${INSTDIR}/usr/share/grommunio-admin-common/traffic-sm.conf"
        rm -fv "${INSTDIR}/usr/share/grommunio-admin-common/traffic-dfl.conf"
```

**Comment by grantma** [comment]
Will have a look at it tomorrow...

**Comment by grantma** [comment]
Hi!

The work is done.  It should be out in the apt repos.

Thank you for pointing it out.

Kindest Regards,

Matt Grant
